### ISSUE TITLE
Handle one-to-many regulation-relation-to-activities in model

### ISSUE THREAD

**Issue by dustine32** [dustine32/signor2gocam#2]
From Paul's (@thomaspd) email:

"The main issue remaining is to handle the one:many issue.  For example, there’s probably only one relationship in SIGNOR where, say, where ATR directly positively regulates ATM.  But there are many different activities of ATM where ATM regulates different downstream activities (BRCA1, CHEK2, MDM2, etc.).  This means the Noctua model will need to connect ATR activity to ALL of the different ATM activities with directly positively regulates relations.  Right now ATR’s activity is only connected to one of the ATM activities (the one where it’s acting on MDM2)."

I think this is what we want?
![image](https://user-images.githubusercontent.com/2678599/37315112-20dd1d2e-2615-11e8-9f47-87166e5456d9.png)
Note: the two ATM nodes connected to ABL1 are for two different activities (protein kinase activity and protein binding).

**Comment by thomaspd** [comment]
Yes, looks right to me.

**Comment by dustine32** [comment]
I figured out a big part of what was wrong here, which was a lack of proper triple-matching used to find existing MF-enabled_by-GP triples. The resulting pathway now shows connected edges from ATR to ABL1 through ATM, though the remaining ATM (with MF protein binding) is still unconnected to ATR:

![image](https://user-images.githubusercontent.com/2678599/37791582-c9074322-2dc6-11e8-90f9-99f7c666bc32.png)

Not totally sure why yet since I do have logic that connects to multiple target MF's per source. I'll have to dig further.

**Comment by dustine32** [comment]
Think I fixed remaining issue with latest commit. I separated out the declaration of entities (GP, MF) before circling back through the pathway spreadsheet and adding the regulation relations. This way, at time of looking for all matching ENTITY B's for a connection, all entities would exist. You can see the full ATR-ATM-ABL1 connections here:

![image](https://user-images.githubusercontent.com/2678599/37843768-1877ca0a-2e83-11e8-8f43-e9276b80a2fa.png)
