### ISSUE TITLE
can't find util import OntologyTerm

### ISSUE THREAD

**Issue by jdr0887** [dustine32/signor2gocam#24]
Where does this dependency come from?

https://github.com/geneontology/signor2gocam/blob/b4e9b01088728d643cd701148896fc4533a3dfcb/pathway_importer.py#L8

**Comment by dustine32** [comment]
@jdr0887 Oh crazy, I guess this means I hadn't yet tested a fresh `git clone` and run of this script before. Sorry! As you can see I just committed the missing `util.py` file.
